services:
  postgres:
    image: postgres:15
    container_name: hotel-postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - hotel_pg_data:/var/lib/postgresql/data
    networks:
      - hotel-network

  app:
    build: .
    image: hotel-app
    container_name: hotel-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    networks:
      - hotel-network

networks:
  hotel-network:

volumes:
  hotel_pg_data: